- name: Deploy to VPS
  uses: appleboy/ssh-action@v0.1.5
  with:
    host: ${{ secrets.VPS_HOST }}
    username: ${{ secrets.VPS_USER }}
    key: ${{ secrets.VPS_KEY }}
    port: 22
    passphrase: ${{ secrets.VPS_PASSPHRASE }}
    script: |
      cd /root/codteech
      ./deploy.sh
