name: Deploy to VPS

on:
  push:
    branches:
      - main  # Aciona o deploy ao fazer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.VPS_KEY }}
        passphrase: ${{ secrets.VPS_PASSPHRASE }}
        port: 22
        script: |
          cd /root/codteech
          ./deploy.sh
